//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chevaca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logs_API
    {
        public int Log_API_ID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Metodo { get; set; }
        public string Body { get; set; }
        public string JSON { get; set; }
        public string Gateway { get; set; }
        public string Nodo { get; set; }
        public string Altitud { get; set; }
        public string Hdop { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
    }
}
