//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chevaca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ovejas_historial_pesadas
    {
        public int Historial_animales_pesadas_ID { get; set; }
        public decimal Peso { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Animal_ID { get; set; }
    }
}
