//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chevaca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class raciones
    {
        public int Racion_ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Aportes_energia_ID { get; set; }
        public Nullable<int> Aportes_mineral_ID { get; set; }
        public Nullable<int> Aportes_proteina_ID { get; set; }
    }
}
