//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chevaca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabajadores
    {
        public int Trabajador_ID { get; set; }
        public int Estancia_ID { get; set; }
    }
}
